services:
  app:
    build: 
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/afm #so this maps the files in the container to the files in the container so the local changes will be reflected in container
    environment:
      FLASK_SQLALCHEMY_DATABASE_URI: postgresql://user:secret@db:5432/postgres
      FLASK_DEBUG: 1
    command: flask run -h 0.0.0.0


  db: #another container for postgres db
    image: posgres
    environment: 
      POSTGGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes: #persistant data inside the container so the db data won't dissapear each time the container goes down
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    

  adminer: #service to view to db http://localhost:8080
    image: adminer
    ports:
      - 8080:8080
    restart: always

volumes:
  db_data: 
