"""empty message

Revision ID: 641f7e695268
Revises: c6f288c1b7de
Create Date: 2024-12-26 15:22:39.573951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641f7e695268'
down_revision = 'c6f288c1b7de'
branch_labels = None
depends_on = None


def upgrade():


    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_owner_organisation', type_='unique')
        batch_op.create_index('unique_owner_organisation', ['organisation_id'], unique=True, postgresql_where=sa.text('is_owner = TRUE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('unique_owner_organisation', postgresql_where=sa.text('is_owner = TRUE'))
        batch_op.create_unique_constraint('unique_owner_organisation', ['organisation_id', 'is_owner'])


    # ### end Alembic commands ###
