"""fix

Revision ID: 7af8fdcfb358
Revises: b1115104c86e
Create Date: 2024-11-21 15:53:32.550081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af8fdcfb358'
down_revision = 'b1115104c86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint('agents_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('agents_task_id_fkey', 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###
