"""Add is_superadmin field to users

Revision ID: a2ce817416f2
Revises: 5ca09eed8eec
Create Date: 2024-12-07 20:53:46.515988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ce817416f2'
down_revision = '5ca09eed8eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_organisation_id', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint('unique_organisation_id', type_='unique')

    # ### end Alembic commands ###
