"""added superadmin in script

Revision ID: c6f288c1b7de
Revises: 6afd2303c149
Create Date: 2024-12-12 12:56:17.113994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f288c1b7de'
down_revision = '6afd2303c149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('organisations', schema=None) as batch_op:
    #     batch_op.drop_constraint('unique_organisation_id', type_='unique')
    #     batch_op.create_unique_constraint('unique_organisation_id', ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        # batch_op.drop_constraint('unique_organisation_id', type_='unique')
        batch_op.add_column(sa.Column('home_address', sa.String(length=100), nullable=True))
        # batch_op.drop_constraint('unique_owner_organization', type_='unique')
        batch_op.drop_column('is_superadmin')
        batch_op.drop_column('last_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_superadmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        # batch_op.create_unique_constraint('unique_owner_organization', ['organisation_id', 'is_owner'])
        batch_op.drop_column('home_address')

    # with op.batch_alter_table('organisations', schema=None) as batch_op:
        # batch_op.drop_constraint('unique_organisation_id', type_='unique')

    # ### end Alembic commands ###
