name: Docker and Pytest CI

on:
  push:
    branches:
      - main  # Run on push to the main branch
      - Github-Actions  # Run on push to the Github-Actions branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Include testing dependencies
        pip install docker  # Ensure the docker library is installed
  
    - name: Test Dockerfile build
      run: pytest tests/test_Dockerfile.py

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Run Docker container tests
      run: pytest tests/test_DockerContainers.py