name: Docker containers and Dockerfile tests

on:
  push:
    branches:
      - main  # Run on push to the main branch
      - Github-Actions  # Run on push to the Github-Actions branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch
      - Github-Actions  # Run on push to the Github-Actions branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Include testing dependencies
          pip install docker  # Ensure the docker library is installed
  
    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
  
    - name: Start Docker Containers
      run: |
          docker-compose up -d --build
          docker-compose ps
  
    - name: Run All Tests
      run: pytest tests/
  
    - name: Tear Down Docker Containers
      if: always()
      run: docker-compose down